export const data = [
  {
    title: '<strong>Interpretation</strong> The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.',
  },
  {
    title: '<strong>Definitions</strong> For the purposes of this Privacy Policy:',
  },
  {
    title: '<strong>Account</strong> means a unique account created for You to access our Service or parts of our Service. ',
  },
  {
    title:
      '<strong>Business,</strong> for the purpose of the CCPA (California Consumer Privacy Act), refers to the Company as the legal entity that collects Consumers’ personal information and determines the purposes and means of the processing of Consumers’ personal information, or on behalf of which such information is collected and that alone, or jointly with others, determines the purposes and means of the processing of consumers’ personal information, that does business in the State of California. ',
  },
  {
    title: '<strong>Company</strong> (referred to as either “the Company”, “We”, “Us” or “Our” in this Agreement) refers to NettyArt,',
  },
  {
    title:
      '<strong>Consumer,</strong> for the purpose of the CCPA (California Consumer Privacy Act), means a natural person who is a California resident. A resident, as defined in the law, includes (1) every individual who is in the USA for other than a temporary or transitory purpose, and (2) every individual who is domiciled in the USA who is outside the USA for a temporary or transitory purpose.',
  },
  {
    title: '<strong>Cookies</strong>  are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.',
  },
  {
    title: '<strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.',
  },
  {
    title: '<strong>Do Not Track</strong>  (DNT) is a concept that has been promoted by US regulatory authorities, in particular the U.S. Federal Trade Commission (FTC), for the Internet industry to develop and implement a mechanism for allowing internet users to control the tracking of their online activities across websites.',
  },
  {
    title: '<strong>Personal Data</strong> is any information that relates to an identified or identifiable individual. For the purposes of the CCPA, Personal Data means any information that identifies, relates to, describes or is capable of being associated with, or could reasonably be linked, directly or indirectly, with You.',
  },
  {
    title: '<strong>Sale</strong> , for the purpose of the CCPA (California Consumer Privacy Act), means selling, renting, releasing, disclosing, disseminating, making available, transferring, or otherwise communicating orally, in writing, or by electronic or other means, a Consumer’s personal information to another business or a third party for monetary or other valuable consideration.',
  },
  {
    title: '<strong>Service</strong> refers to the Website.',
  },
  {
    title: '<strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.',
  },
  {
    title: '<strong>Third-party Social Media Service</strong>  refers to any website or any social network website through which a User can log in or create an account to use the Service.',
  },
  {
    title: '<strong>Usage Data</strong>  refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit). <a href="http://www.nettyworth.io" target="_blank" rel="noreferrer noopener" data-wpel-link="internal">www.nettyworth.io</a>',
  },
  {
    title:
      '<strong>Website</strong>  refers to <a href="https://nettyworth.io/" target="_blank" rel="noreferrer noopener" data-wpel-link="internal"></a><a href="http://www.nettyworth.io" target="_blank" rel="noreferrer noopener" data-wpel-link="internal">www.nettyworth.io</a> , accessible from <a href="http://www.nettyworth.io" target="_blank" rel="noreferrer noopener" data-wpel-link="internal">www.nettyworth.io</a>',
  },
  {
    title:
      '<strong>You</strong>  refers to <a href="https://nettyworth.io/" target="_blank" rel="noreferrer noopener" data-wpel-link="internal"></a><a href="http://www.nettyworth.io" target="_blank" rel="noreferrer noopener" data-wpel-link="internal">www.nettyworth.io</a> , accessible from <a href="http://www.nettyworth.io" target="_blank" rel="noreferrer noopener" data-wpel-link="internal">www.nettyworth.io</a>',
  },
  {
    title: '<strong>Collecting and Using Your Personal Data</strong> Types of Data Collected',
  },
  {
    title: '<strong>Collecting and Using Your Personal Data</strong> Types of Data Collected',
  },
  {
    title:
      '<strong>Personal Data</strong> While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to: <br/> Email address <br/> First name and last name <br/> Phone number <br/> Address, State, Province, ZIP/Postal code, City <br/> Usage Data',
  },
  {
    title: '<strong>Usage Data</strong> Usage Data is collected automatically when using the Service.',
  },
  {
    title:
      '<strong>Usage Data</strong> Usage Data is collected automatically when using the Service. <br/> Usage Data may include information such as Your Device’s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data. <br/> When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data. <br/> We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.',
  },
];

export const dots = [
  {
    title:
      '<strong>Cookies or Browser Cookies</strong> . Certain features of our Service may use local stored objects (or Flash Cookies) to collect and store information about Your preferences or Your activity on our Service. Flash Cookies are not managed by the same browser settings as those used for Browser Cookies. For more information on how You can delete Flash Cookies, please read “Where can I change the settings for disabling, or deleting local shared objects?” available at ',
  },
  {
    title: '<strong>Flash Cookies</strong> . A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.',
  },
  {
    title:
      '<strong>Web Beacons</strong> . Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity). <br/> Cookies can be “Persistent” or “Session” Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser. You can learn more about cookies here: All About Cookies by TermsFeed. <br/> We use both Session and Persistent Cookies for the purposes set out below:',
  },
];

export const necessary = [
  {
    title:
      '<strong>Necessary / Essential Cookies</strong> <br/> Type: Session Cookies <br/> Administered by: Us <br/> Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services. <br/>',
  },
  {
    title: '<strong>Cookies Policy / Notice Acceptance Cookies</strong> <br/> Type: Persistent Cookies <br/> Administered by: Us <br/> Purpose: These Cookies identify if users have accepted the use of cookies on the Website. <br/>',
  },
  {
    title:
      '<strong>Functionality Cookies</strong> <br/> Type: Persistent Cookies <br/> Administered by: Us <br/> Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website. <br/>',
  },
  {
    title:
      '<strong>Tracking and Performance Cookies</strong> <br/> Type: Persistent Cookies <br/> Administered by: Third-Parties <br/> Purpose: These Cookies are used to track information about traffic to the Website and how users use the Website. The information gathered via these Cookies may directly or indirectly identify you as an individual visitor. This is because the information collected is typically linked to a pseudonymous identifier associated with the device you use to access the Website. We may also use these Cookies to test new pages, features or new functionality of the Website to see how our users react to them. <br/>',
  },
  {
    title:
      '<strong>Tracking and Performance Cookies</strong> <br/> Type: Persistent Cookies <br/> Administered by: Third-Parties <br/> Purpose: These Cookies are used to track information about traffic to the Website and how users use the Website. The information gathered via these Cookies may directly or indirectly identify you as an individual visitor. This is because the information collected is typically linked to a pseudonymous identifier associated with the device you use to access the Website. We may also use these Cookies to test new pages, features or new functionality of the Website to see how our users react to them. <br/>',
  },
  {
    title:
      '<strong>Tracking and Performance Cookies</strong> <br/> Type: Persistent Cookies <br/> Administered by: Third-Parties <br/> Purpose: These Cookies are used to track information about traffic to the Website and how users use the Website. The information gathered via these Cookies may directly or indirectly identify you as an individual visitor. This is because the information collected is typically linked to a pseudonymous identifier associated with the device you use to access the Website. We may also use these Cookies to test new pages, features or new functionality of the Website to see how our users react to them. <br/>',
  },
  {
    title:
      '<strong>Targeting and Advertising Cookies</strong> <br/> Type: Persistent Cookies <br/> Administered by: Third-Parties <br/> Purpose: These Cookies track your browsing habits to enable Us to show advertising which is more likely to be of interest to You. These Cookies use information about your browsing history to group You with other users who have similar interests. Based on that information, and with Our permission, third party advertisers can place Cookies to enable them to show adverts which We think will be relevant to your interests while You are on third party websites.  <br/>  For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy.',
  },
  {
    title: '<strong>Use of Your Personal Data</strong> <br/> The Company may use Personal Data for the following purposes:',
  },
];

export const provide = [
  {
    title: '<strong>To provide and maintain our Service</strong> <br/> , including to monitor the usage of our Service.',
  },
  {
    title: '<strong>To manage Your Account: </strong> <br/> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.',
  },
  {
    title: '<strong>For the performance of a contract: </strong> <br/> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.',
  },
  {
    title:
      '<strong>To contact You:</strong> <br/>  To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application’s push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.',
  },
  {
    title:
      '<strong>To provide You with news</strong> <br/> , special <a class="glossaryLink" aria-describedby="tt" data-cmtooltip="<div class=glossaryItemTitle>Offers</div><div class=glossaryItemBody>&amp;lt;!-- wp:paragraph --&amp;gt;Interested buyers of a specific edition of a collectible are able to make offers to the owner in hopes of purchasing the NFT at their desired price.&amp;lt;br/&amp;gt;&amp;lt;!-- /wp:paragraph --&amp;gt;</div>" href="https://nettyworth.io/glossary/offers/" data-gt-translate-attributes="[{&quot;attribute&quot;:&quot;data-cmtooltip&quot;, &quot;format&quot;:&quot;html&quot;}]" data-wpel-link="internal">offers</a>   and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.',
  },
  {
    title: '<strong>To manage Your requests: </strong> <br/> To attend and manage Your requests to Us.',
  },
  {
    title: '<strong>To deliver targeted advertising to You:</strong> <br/>  We may use Your information to develop and display content and advertising (and work with third-party vendors who do so) tailored to Your interests and/or location and to measure its effectiveness.',
  },
  {
    title:
      '<strong>For business transfers:</strong> <br/>  We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.',
  },
  {
    title: '<strong>For other purposes:</strong> <br/>  We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience. <br/> We may share Your personal information in the following situations:',
  },
  {
    title: '<strong>With Service Providers:</strong> <br/> We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to show advertisements to You to help support and maintain Our Service, to advertise on third party websites to You after You visited our Service, for payment processing, to contact You.',
  },
  {
    title: '<strong>For business transfers:</strong> <br/>  We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.',
  },
  {
    title: '<strong>With Affiliates:</strong> <br/>  We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.',
  },
  {
    title: '<strong>With business partners:</strong> <br/>  We may share Your information with Our business partners to offer You certain products, services or promotions.',
  },
  {
    title:
      '<strong>With other users:</strong> <br/> when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside. If You interact with other users or register through a Third-Party Social Media Service, Your contacts on the Third-Party Social Media Service may see Your name, profile, pictures and description of Your activity. Similarly, other users will be able to view descriptions of Your activity, communicate with You and view Your profile.',
  },
  {
    title: '<strong>With Your consent:</strong> <br/>  We may disclose Your personal information for any other purpose with Your consent.',
  },
];

export const personalData = [
  {
    title:
      '<strong>Retention of Your Personal Data</strong> <br/> The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies. <br/> The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.',
  },
  {
    title:
      '<strong>Transfer of Your Personal Data</strong> <br/>Your information, including Personal Data, is processed at the Company’s operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction. <br/> Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer. <br/> The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.',
  },
  {
    title: '<strong>Disclosure of Your Personal Data</strong>',
  },
  {
    title: '<strong>Business Transactions</strong> If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.',
  },
  {
    title: '<strong>Law enforcement</strong> Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).',
  },
  {
    title: '<strong>Other legal requirements</strong> The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:',
  },
];

export const legalDots = [
  {
    title: 'Comply with a legal obligation',
  },
  {
    title: 'Protect and defend the rights or property of the Company',
  },
  {
    title: 'Prevent or investigate possible wrongdoing in connection with the Service',
  },
  {
    title: 'Protect the personal safety of Users of the Service or the public',
  },
  {
    title: 'Protect against legal liability',
  },
];

export const security = [
  {
    title:
      '<strong>Security of Your Personal Data</strong> <br/> The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal <br/> Data, We cannot guarantee its absolute security.Detailed Information on the Processing of Your Personal Data Service Providers have access to Your Personal Data only to perform their tasks on Our behalf and are obligated not to disclose or use it for any other purpose.',
  },
  {
    title: '<strong>Analytics</strong> <br/> We may use third-party Service providers to monitor and analyze the use of our Service.',
  },
  {
    title:
      '<strong>Google Analytics</strong> <br/> Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualize and personalize the ads of its own advertising network. <br/> You can opt-out of having made your activity on the Service available to Google Analytics by installing the Google Analytics opt-out browser add-on. The add-on prevents the Google Analytics JavaScript (ga.js, analytics.js and dc.js) from sharing information with Google Analytics about visits activity. </br> For more information on the privacy practices of Google, please visit the Google Privacy &amp; Terms web page: <a href="https://policies.google.com/privacy" target="_blank" rel="noreferrer noopener nofollow external" data-wpel-link="external">https://policies.google.com/privacy</a>',
  },
  {
    title: '<strong>Advertising</strong><br/> We may use Service providers to show advertisements to You to help support and maintain Our Service.',
  },
  {
    title:
      '<strong>Google AdSense &amp; DoubleClick Cookie</strong> <br/> Google, as a third party vendor, uses cookies to serve ads on our Service. Google’s use of the DoubleClick cookie enables it and its partners to serve ads to our users based on their visit to our Service or other websites on the Internet. <br/> You may opt out of the use of the DoubleClick Cookie for interest-based advertising by visiting the Google Ads Settings web page: <a href="https://www.google.com/ads/preferences/" target="_blank" rel="noreferrer noopener nofollow external" data-wpel-link="external">https://www.google.com/ads/preferences/</a>',
  },
  {
    title:
      '<strong>Email Marketing</strong> <br/> We may use Your Personal Data to contact You with newsletters, marketing or promotional materials and other information that may be of interest to You. You may opt-out of receiving any, or all, of these communications from Us by following the unsubscribe link or instructions provided in any email We send or by contacting Us. <br/> We may use Email Marketing Service Providers to manage and send emails to You.',
  },
  {
    title:
      '<strong>Mailchimp</strong> <br/> Mailchimp is an email marketing sending service provided by The Rocket Science Group LLC. <br/> For more information on the privacy practices of Mailchimp, please visit their Privacy policy: <a href="https://mailchimp.com/legal/privacy/" target="_blank" rel="noreferrer noopener nofollow external" data-wpel-link="external">https://mailchimp.com/legal/privacy/</a>',
  },
  {
    title:
      '<strong>Payments</strong> <br/> We may provide paid products and/or services within the Service. In that case, we may use third-party services for payment processing (e.g. payment processors). <br/> We will not store or collect Your payment card details. That information is provided directly to Our third-party payment processors whose use of Your personal information is governed by their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council, which is a joint effort of brands like Visa, Mastercard, American Express and Discover. PCI-DSS requirements help ensure the secure handling of payment information. <br/> Behavioral Remarketing <br/>The Company uses remarketing services to advertise on third-party websites to You after You visited our Service. We and Our third-party vendors use cookies and non-cookie technologies to help Us recognize Your Device and understand how You use our Service so that We can improve our Service to reflect Your interests and serve You advertisements that are likely to be of more interest to You. <br/> These third-party vendors collect information about Your activity on Our Service to enable Us to:',
  },
];

export const securityDots = [
  {
    title: 'Measure and analyze traffic and browsing activity on Our Service',
  },
  {
    title: 'Show advertisements for our products and/or services to You on third-party websites',
  },
  {
    title:
      'Measure and analyze the performance of Our advertising campaigns Some of these third-party vendors may use non-cookie technologies that may not be impacted by browser settings that block cookies. Your browser may not permit You to block such technologies. You can use the following third-party tools to decline the collection and use of information for the purpose of serving You interest-based advertising:',
  },
  {
    title: 'The NAI’s opt-out platform: <a href="http://www.networkadvertising.org/choices/" target="_blank" rel="noreferrer noopener nofollow external" data-wpel-link="external">http://www.networkadvertising.org/choices/</a>',
  },
  {
    title: 'The EDAA’s opt-out platform <a href="http://www.youronlinechoices.com/" target="_blank" rel="noreferrer noopener nofollow external" data-wpel-link="external">http://www.youronlinechoices.com/</a>',
  },
  {
    title:
      'The DAA’s opt-out platform: http://optout.aboutads.info/?c=2&amp;lang=EN <br/> We may share information, such as hashed email addresses (if available) or other online identifiers collected on Our Service with these third-party vendors. This allows Our third-party vendors to recognize and deliver You ads across devices and browsers. To read more about the technologies used by these third-party vendors and their cross-device capabilities please refer to the Privacy Policy of each vendor listed below. <br/> <br/> The third-party vendors We use are: <br/> <br/> Google also recommends installing the Google Analytics Opt-out Browser Add-on – https://tools.google.com/dlpage/gaoptout – for your web browser. Google Analytics Opt-out Browser Add-on provides visitors with the ability to prevent their data from being collected and used by Google Analytics. <br/> <br/> For more information on the privacy practices of Google, please visit the Google Privacy &amp; Terms web page:  <a href="https://policies.google.com/privacy" target="_blank" rel="noreferrer noopener nofollow external" data-wpel-link="external">https://policies.google.com/privacy</a>',
  },
];

export const ads = [
  {
    title:
      '<strong>Google Ads (AdWords)</strong> <br/> Google Ads (AdWords) remarketing service is provided by Google Inc. <br/> <br/> You can opt-out of Google Analytics for Display Advertising and customize the Google Display Network ads by visiting the Google Ads Settings page: <a href="http://www.google.com/settings/ads" target="_blank" rel="noreferrer noopener nofollow external" data-wpel-link="external">http://www.google.com/settings/ads</a>',
  },
  {
    title:
      '<strong>AdRoll</strong> <br/> AdRoll remarketing service is provided by NextRoll, Inc. <br/> <br/> You can opt-out of AdRoll remarketing by visiting this AdRoll Advertising Preferences web page: http://info.evidon.com/pub_info/573?v=1&amp;nt=1&amp;nw=false or the Opt Out of Personalized Advertising web page: https://help.adroll.com/hc/en-us/articles/216599538-Opting-Out-of-Personalized-Advertising <br/> <br/> If You are a California resident, please read the “Information For California Residents Only” section in the Privacy Policy of NextRoll, Inc.: <a href="https://www.nextroll.com/privacy#service-13" target="_blank" rel="noreferrer noopener nofollow external" data-wpel-link="external">https://www.nextroll.com/privacy#service-13</a> <br/> <br/> For more information on the privacy practices of AdRoll, please visit the NextRoll, Inc. Privacy Policy web page: <a href="https://www.nextroll.com/privacy" target="_blank" rel="noreferrer noopener nofollow external" data-wpel-link="external">https://www.nextroll.com/privacy</a>',
  },
  {
    title: '<strong>Usage, Performance and Miscellaneous</strong> <br/> We may use third-party Service Providers to provide better improvement of our Service.',
  },
  {
    title:
      '<strong>Google Places</strong> <br/> Google Places is a service that returns information about places using HTTP requests. It is operated by Google <br/>  Google Places service may collect information from You and from Your Device for security purposes. <br/> The information gathered by Google Places is held in accordance with the Privacy Policy of Google: https://www.google.com/intl/en/policies/privacy/',
  },
  {
    title: '<strong>CCPA Privacy</strong> <br/> This privacy notice section for California residents supplements the information contained in Our Privacy Policy and it applies solely to all visitors, users, and others who reside in the State of California.',
  },
  {
    title:
      '<strong>Categories of Personal Information Collected</strong> <br/> We collect information that identifies, relates to, describes, references, is capable of being associated with, or could reasonably be linked, directly or indirectly, with a particular Consumer or Device. The following is a list of categories of personal information which we may collect or may have been collected from California residents within the last twelve (12) months. <br/> <br/> Please note that the categories and examples provided in the list below are those defined in the CCPA. This does not mean that all examples of that category of personal information were in fact collected by Us, but reflects our good faith belief to the best of our knowledge that some of that information from the applicable category may be and may have been collected. For example, certain categories of personal information would only be collected if You provided such personal information directly to Us.',
  },
  {
    title: '<strong>Category A: Identifiers.</strong> <br/> Examples: A real name, alias, postal address, unique personal identifier, online identifier, Internet Protocol address, email address, account name, driver’s license number, passport number, or other similar identifiers. <br/> <br/> Collected: Yes.',
  },
  {
    title:
      '<strong>Category B: Personal information categories listed in the California Customer</strong> <br/> Records statute (Cal. Civ. Code § 1798.80(e)). <br/> <br/> Examples: A name, signature, Social Security number, physical characteristics or description, address, telephone number, passport number, driver’s license or state identification card number, insurance policy number, education, employment, employment history, bank account number, credit card number, debit card number, or any other financial information, medical information, or health insurance information. Some personal information included in this category may overlap with other categories. <br/> <br/> Collected: Yes. <br/> <br/>',
  },
  {
    title:
      '<strong>Category C: Protected classification characteristics under California or federal law.</strong> <br/> Examples: Age (40 years or older), race, color, ancestry, national origin, citizenship, religion or creed, marital status, medical condition, physical or mental disability, sex (including gender, gender identity, gender expression, pregnancy or childbirth and related medical conditions), sexual orientation, veteran or military status, genetic information (including familial genetic information). <br/> <br/> Collected: No. <br/> <br/>',
  },
  {
    title: '<strong>Category D: Commercial information.</strong> <br/> Examples: Records and history of products or services purchased or considered. <br/> <br/> Collected: Yes. <br/> <br/> ',
  },
  {
    title:
      '<strong>Category E: Biometric information.</strong> <br/> Examples: Genetic, physiological, behavioral, and biological characteristics, or activity patterns used to extract a template or other identifier or identifying information, such as, fingerprints, faceprints, and voiceprints, iris or retina scans, keystroke, gait, or other physical patterns, and sleep, health, or exercise data. <br/> Collected: No.',
  },
  {
    title: '<strong>Category F: Internet or other similar network activity.</strong> <br/> Examples: Interaction with our Service or advertisement. <br/> <br/> Collected: Yes. <br/> <br/>',
  },
  {
    title: '<strong>Category G: Geolocation data.</strong> <br/> Examples: Approximate physical location. <br/> <br/> Collected: No. <br/> <br/>',
  },
  {
    title: '<strong>Category H: Sensory data.</strong> <br/> Examples: Audio, electronic, visual, thermal, olfactory, or similar information. <br/> <br/> Collected: No. <br/> <br/>',
  },
  {
    title: '<strong>Category I: Professional or employment-related information.</strong> <br/> Examples: Current or past job history or performance evaluations. <br/> <br/> Collected: No. <br/> <br/>',
  },
  {
    title:
      '<strong>Category J: Non-public education information (per the Family Educational Rights and Privacy Act (20 U.S.C. Section 1232g, 34 C.F.R. Part 99)).</strong>  <br/> <br/> Examples: Education records directly related to a student maintained by an educational institution or party acting on its behalf, such as grades, transcripts, class lists, student schedules, student identification codes, student financial information, or student disciplinary records. <br/> <br/> Collected: No.',
  },
  {
    title: '<strong>Category K: Inferences drawn from other personal information.</strong>  <br/> Examples: Profile reflecting a person’s preferences, characteristics, psychological trends, predispositions, behavior, attitudes, intelligence, abilities, and aptitudes. <br/> <br/> Collected: No. <br/> Under CCPA, personal information does not include:',
  },
];

export const publicly = [
  {
    title: 'Publicly available information from government records',
  },
  {
    title: 'Deidentified or aggregated consumer information',
  },
  {
    title: 'Information excluded from the CCPA’s scope, such as:',
  },
  {
    title: 'Health or medical information covered by the Health Insurance Portability and Accountability Act of 1996 (HIPAA) and the California Confidentiality of Medical Information Act (CMIA) or clinical trial data',
  },
  {
    title:
      'Personal Information covered by certain sector-specific privacy laws, including the Fair Credit Reporting Act (FRCA), the Gramm-Leach-Bliley Act (GLBA) or California Financial Information Privacy Act (FIPA), and the Driver’s Privacy Protection Act of 1994 Sources of Personal Information We obtain the categories of personal information listed above from the following categories of sources:',
  },
  {
    title: 'Directly from You. For example, from the forms You complete on our Service, preferences You express or provide through our Service, or from Your purchases on our Service.',
  },
  {
    title: 'Indirectly from You. For example, from observing Your activity on our Service.',
  },
  {
    title: 'Automatically from You. For example, through cookies We or our Service Providers set on Your Device as You navigate through our Service.',
  },
  {
    title:
      'From Service Providers. For example, third-party vendors to monitor and analyze the use of our Service, third-party vendors to provide advertising on our Service, third-party vendors to deliver targeted advertising to You, third-party vendors for payment processing, or other third-party vendors that We use to provide the Service to You.Use of Personal Information for Business Purposes or Commercial Purposes We may use or disclose personal information We collect for “business purposes” or “commercial purposes” (as defined under the CCPA), which may include the following examples:',
  },
  {
    title: 'To operate our Service and provide You with our Service.',
  },
  {
    title: 'To provide You with support and to respond to Your inquiries, including to investigate and address Your concerns and monitor and improve our Service.',
  },
  {
    title: 'To fulfill or meet the reason You provided the information. For example, if You share Your contact information to ask a question about our Service, We will use that personal information to respond to Your inquiry. If You provide Your personal information to purchase a product or service, We will use that information to process Your payment and facilitate delivery.',
  },
  {
    title: 'To respond to law enforcement requests and as required by applicable law, court order, or governmental regulations.',
  },
  {
    title: 'As described to You when collecting Your personal information or as otherwise set forth in the CCPA.',
  },
  {
    title: 'For internal administrative and auditing purposes.',
  },
  {
    title:
      'To detect security incidents and protect against malicious, deceptive, fraudulent or illegal activity, including, when necessary, to prosecute those responsible for such activities. <br/> <br/> Please note that the examples provided above are illustrative and not intended to be exhaustive. For more details on how we use this information, please refer to the “Use of Your Personal Data” section. If We decide to collect additional categories of personal information or use the personal information We collected for materially different, unrelated, or incompatible purposes We will update this Privacy Policy. Disclosure of Personal Information for Business Purposes or Commercial Purposes We may use or disclose and may have used or disclosed in the last twelve (12) months the following categories of personal information for business or commercial purposes: <br/> <br/>',
  },
  {
    title: 'Category A: Identifiers',
  },
  {
    title: 'Category B: Personal information categories listed in the California Customer Records statute (Cal. Civ. Code § 1798.80(e))',
  },
  {
    title: 'Category D: Commercial information',
  },
  {
    title:
      'Category F: Internet or other similar network activity Please note that the categories listed above are those defined in the CCPA. This does not mean that all examples of that category of personal information were in fact disclosed, but reflects our good faith belief to the best of our knowledge that some of that information from the applicable category may be and may have been disclosed. <br/> <br/> When We disclose personal information for a business purpose or a commercial purpose, We enter a contract that describes the purpose and requires the recipient to both keep that personal information confidential and not use it for any purpose except performing the contract. <br/> <br/>',
  },
];

export const category = [
  {
    title: 'Category A: Identifiers',
  },
  {
    title: 'Category B: Personal information categories listed in the California Customer Records statute (Cal. Civ. Code § 1798.80(e))',
  },
  {
    title: 'Category D: Commercial information',
  },
  {
    title:
      'Category F: Internet or other similar network activity Please note that the categories listed above are those defined in the CCPA. This does not mean that all examples of that category of personal information were in fact disclosed, but reflects our good faith belief to the best of our knowledge that some of that information from the applicable category may be and may have been disclosed. <br/> <br/> When We disclose personal information for a business purpose or a commercial purpose, We enter a contract that describes the purpose and requires the recipient to both keep that personal information confidential and not use it for any purpose except performing the contract. <br/> <br/>',
  },
  {
    title: 'Service Providers',
  },
  {
    title: 'Payment processors',
  },
  {
    title: 'Our affiliates',
  },
  {
    title: 'Our business partners',
  },
  {
    title:
      'Third party vendors to whom You or Your agents authorize Us to disclose Your personal information in connection with products or services We provide to You <br/> <br/> Sale of Personal Information of Minors Under 16 Years of Age <br/> We do not sell the personal information of Consumers We actually know are less than 16 years of age, unless We receive affirmative authorization (the “right to opt-in”) from either the Consumer who is between 13 and 16 years of age, or the parent or guardian of a Consumer less than 13 years of age. Consumers who opt-in to the sale of personal information may opt-out of future sales at any time. To exercise the right to opt-out, You (or Your authorized representative) may submit a request to Us by contacting Us. <br/> <br/> If You have reason to believe that a child under the age of 13 (or 16) has provided Us with personal information, please contact Us with sufficient detail to enable Us to delete that information.',
  },
];

export const ccpa = [
  {
    title: 'The right to notice. You have the right to be notified which categories of Personal Data are being collected and the purposes for which the Personal Data is being used.',
  },
  {
    title: 'The right to request. Under CCPA, You have the right to request that We disclose information to You about Our collection, use, sale, disclosure for business purposes and share of personal information. Once We receive and confirm Your request, We will disclose to You:',
  },
  {
    title: 'The categories of personal information We collected about You',
  },
  {
    title: 'The categories of sources for the personal information We collected about You',
  },
  {
    title: 'Our business or commercial purpose for collecting or selling that personal information',
  },
  {
    title: 'The categories of third parties with whom We share that personal information',
  },
  {
    title: 'The specific pieces of personal information We collected about You',
  },
  {
    title: 'If we sold Your personal information or disclosed Your personal information for a business purpose, We will disclose to You:',
  },
  {
    title: 'The categories of personal information categories sold',
  },
  {
    title: 'The categories of personal information categories disclosed',
  },
  {
    title: 'The right to say no to the sale of Personal Data (opt-out). You have the right to direct Us to not sell Your personal information. To submit an opt-out request please contact Us.',
  },
  {
    title:
      'The right to delete Personal Data. You have the right to request the deletion of Your Personal Data, subject to certain exceptions. Once We receive and confirm Your request, We will delete (and direct Our Service Providers to delete) Your personal information from our records, unless an exception applies. We may deny Your deletion request if retaining the information is necessary for Us or Our Service Providers to:',
  },
  {
    title: 'Complete the transaction for which We collected the personal information, provide a good or service that You requested, take actions reasonably anticipated within the context of our ongoing business relationship with You, or otherwise perform our contract with You.',
  },
  {
    title: 'Detect security incidents, protect against malicious, deceptive, fraudulent, or illegal activity, or prosecute those responsible for such activities.',
  },
  {
    title: 'Debug products to identify and repair errors that impair existing intended functionality.',
  },
  {
    title: 'Exercise free speech, ensure the right of another consumer to exercise their free speech rights, or exercise another right provided for by law.',
  },
  {
    title: 'Comply with the California Electronic Communications Privacy Act (Cal. Penal Code § 1546 et. seq.).',
  },
  {
    title: 'Engage in public or peer-reviewed scientific, historical, or statistical research in the public interest that adheres to all other applicable ethics and privacy laws, when the information’s deletion may likely render impossible or seriously impair the research’s achievement, if You previously provided informed consent.',
  },
  {
    title: 'Enable solely internal uses that are reasonably aligned with consumer expectations based on Your relationship with Us.',
  },
  {
    title: 'Comply with a legal obligation.',
  },
  {
    title: 'Make other internal and lawful uses of that information that are compatible with the context in which You provided it.',
  },
  {
    title: 'The right not to be discriminated against. You have the right not to be discriminated against for exercising any of Your consumer’s rights, including by:',
  },
  {
    title: 'Denying goods or services to You',
  },
  {
    title: 'Charging different prices or rates for goods or services, including the use of discounts or other benefits or imposing penalties',
  },
  {
    title: 'Providing a different level or quality of goods or services to You',
  },
  {
    title: 'Suggesting that You will receive a different price or rate for goods or services or a different level or quality of goods or services <br/> Exercising Your CCPA Data Protection Rights <br/> In order to exercise any of Your rights under the CCPA, and if You are a California resident, You can contact Us:',
  },
  {
    title: 'By email: Info@NettyArt.io <br/> Only You, or a person registered with the California Secretary of State that You authorize to act on Your behalf, may make a verifiable request related to Your personal information.',
  },
];

export const requestDots = [
  {
    title: 'Provide sufficient information that allows Us to reasonably verify You are the person about whom We collected personal information or an authorized representative',
  },
  {
    title: 'Describe Your request with sufficient detail that allows Us to properly understand, evaluate, and respond to it <br/> We cannot respond to Your request or provide You with the required information if We cannot:',
  },
  {
    title: 'Verify Your identity or authority to make the request',
  },
  {
    title:
      'And confirm that the personal information relates to You <br/> We will disclose and deliver the required information free of charge within 45 days of receiving Your verifiable request. The time period to provide the required information may be extended once by an additional 45 days when reasonably necessary and with prior notice. <br/> <br/>  Any disclosures We provide will only cover the 12-month period preceding the verifiable request’s receipt. <br/> <br/> For data portability requests, We will select a format to provide Your personal information that is readily useable and should allow You to transmit the information from one entity to another entity without hindrance. <br/> <br/> <strong>Do Not Sell My Personal Information</strong> <br/> You have the right to opt-out of the sale of Your personal information. Once We receive and confirm a verifiable consumer request from You, we will stop selling Your personal information. To exercise Your right to opt-out, please contact Us. <br/> The Service Providers we partner with (for example, our analytics or advertising partners) may use technology on the Service that sells personal information as defined by the CCPA law. If you wish to opt out of the use of Your personal information for interest-based advertising purposes and these potential sales as defined under CCPA law, you may do so by following the instructions below. <br/> Please note that any opt out is specific to the browser You use. You may need to opt out on every browser that You use. <br/> <br/> <strong>Website</strong> <br/> You can opt out of receiving ads that are personalized as served by our Service Providers by following our instructions presented on the Service:',
  },
  {
    title: 'The NAI’s opt-out platform: http://www.networkadvertising.org/choices/',
  },
  {
    title: 'The EDAA’s opt-out platform http://www.youronlinechoices.com/',
  },
  {
    title:
      'The DAA’s opt-out platform: http://optout.aboutads.info/?c=2&amp;lang=EN <br/> The opt out will place a cookie on Your computer that is unique to the browser You use to opt out. If you change browsers or delete the cookies saved by your browser, You will need to opt out again. <br/> Mobile Devices <br/> Your mobile device may give You the ability to opt out of the use of information about the apps You use in order to serve You ads that are targeted to Your interests: <br/>',
  },
  {
    title: '“Opt out of Interest-Based Ads” or “Opt out of Ads Personalization” on Android devices',
  },
  {
    title:
      '“Limit Ad Tracking” on iOS devices <br/> You can also stop the collection of location information from Your mobile device by changing the preferences on Your mobile device. <br/> “Do Not Track” Policy as Required by California Online Privacy Protection Act (CalOPPA) <br/> <br/> <strong>Our Service does not respond to Do Not Track signals.</strong> <br/> However, some third party websites do keep track of Your browsing activities. If You are visiting such websites, You can set Your preferences in Your web browser to inform websites that You do not want to be tracked. You can enable or disable DNT by visiting the preferences or settings page of Your web browser. <br/> <br/> <strong>Your California Privacy Rights (California’s Shine the Light law)</strong> <br/>  Under California Civil Code Section 1798 (California’s Shine the Light law), California residents with an established business relationship with us can request information once a year about sharing their Personal Data with third parties for the third parties’ direct marketing purposes. <br/> <br/> If you’d like to request more information under the California Shine the Light law, and if You are a California resident, You can contact Us using the contact information provided below. <br/> <br/> <strong>California Privacy Rights for Minor Users (California Business and Professions Code Section 22581)</strong> <br/> California Business and Professions Code section 22581 allows California residents under the age of 18 who are registered users of online sites, services or applications to request and obtain removal of content or information they have publicly posted. <br/> To request removal of such data, and if You are a California resident, You can contact Us using the contact information provided below, and include the email address associated with Your account. <br/> <br/> Be aware that Your request does not guarantee complete or comprehensive removal of content or information posted online and that the law may not permit or require removal in certain circumstances. <br/> <br/> <strong><br>Links to Other Websites</strong> <br/> Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party’s site. We strongly advise You to review the Privacy Policy of every site You visit. <br/> We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services. <br/> <br/> <strong>Changes to this Privacy Policy</strong> <br/> We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page. <br/> We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the “Last updated” date at the top of this  <br/> <br/>  <strong>Privacy Policy.</strong> <br/> You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page. <br/> <br/> <strong>Contact Us</strong> <br/> If you have any questions about this Privacy Policy, You can contact us: By email: <a className="text-primary" href="mailto:Info@NettyArt.io">Info@NettyArt.io</a>',
  },
];
