#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Disable concurent to run build-types after ESLint in lint-staged
npx lint-staged --concurrent false
npx tsc --noEmit && npx eslint --fix . && npx prettier --write .
